spring:
  application:
    name: library-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: library-user-service
          uri: lb://LIBRARY-USER-SERVICE
          predicates:
            - Path=/users/**,/auth/**
          filters:
            - RewritePath=/users/(?<segment>.*), /users/${segment}

        - id: book-service
          uri: lb://library-book-service
          predicates:
            - Path=/books/**
          filters:
            - RewritePath=/books/(?<segment>.*), /books/${segment}

        - id: borrowing-service
          uri: lb://library-borrowing-service
          predicates:
            - Path=/borrowings/**
          filters:
            - RewritePath=/borrowings/(?<segment>.*), /borrowings/${segment}

        - id: notification-service
          uri: lb://library-notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - RewritePath=/notifications/(?<segment>.*), /notifications/${segment}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
